"use client";
import { useState } from "react";
import { DISCORD } from "../data";
export default function PartnerApplication() {
  const [name,setName]=useState("");const [kind,setKind]=useState("Minecraft community");const [link,setLink]=useState("");const [contact,setContact]=useState("");const [audience,setAudience]=useState("");const [idea,setIdea]=useState("");const [offer,setOffer]=useState("");const [needs,setNeeds]=useState("");const [rules,setRules]=useState("");const [allowed,setAllowed]=useState(false);const [draft,setDraft]=useState("");const [status,setStatus]=useState("");
  const application=()=>`Booger Client partnership application\n\nCommunity / creator: ${name.trim()}\nType: ${kind}\nPublic link: ${link.trim()}\nDiscord contact: ${contact.trim()}\nAudience / activity: ${audience.trim() || "Not provided"}\n\nCollaboration idea:\n${idea.trim()}\n\nWhat we can offer:\n${offer.trim()}\n\nWhat we would need from Booger Client:\n${needs.trim()}\n\nPartnership rules / requirements:\n${rules.trim() || "To discuss"}\n\nI confirm I can discuss collaborations for this community and have checked its partnership rules.\n\nThis is an application for discussion, not an accepted agreement.`;
  async function copy(){try{await navigator.clipboard.writeText(draft);setStatus("Application copied. Open Discord and send it to the Booger Client team. It has not been sent automatically.");}catch{setStatus("Clipboard unavailable. Select the text below or download it instead.");}}
  function download(){const u=URL.createObjectURL(new Blob([draft],{type:"text/plain"}));const a=document.createElement("a");a.href=u;a.download="booger-partnership-application.txt";a.click();URL.revokeObjectURL(u);setStatus("Application downloaded. Review it and send it to the team on Discord.");}
  return <div className="partnerLayout"><aside className="toolCard partnerInfo"><p className="microLabel">LET&apos;S BUILD TOGETHER</p><h2>A good fit matters.</h2><p>We&apos;re interested in Minecraft creators, server networks, PvP communities, modding communities, and groups that share our interest in customization and a better player experience.</p><h3>Tell us your idea</h3><p>Explain what makes your community relevant, what you can offer, and what you would need from us. Audience size is useful context; activity and relevance matter too.</p><h3>Respect your community</h3><p>Check your server&apos;s partnership rules before applying. Please represent a community you have permission to discuss collaborations for.</p><h3>What happens next?</h3><ol><li>Fill out the application.</li><li>Review and copy or download it.</li><li>Join Discord and send it to the Booger Client team through an appropriate support channel.</li></ol><p className="smallNote">Applications are reviewed individually. Applying does not guarantee acceptance or authorize payments, exclusivity, or other commitments.</p></aside>
  <section className="toolCard partnerForm"><p className="microLabel">PARTNER APPLICATION</p><h2>Introduce your community.</h2><p>This form prepares your application locally. It does not submit it automatically. Don&apos;t include passwords, private member lists, or other confidential information.</p><form onSubmit={e=>{e.preventDefault();if(!allowed)return;setDraft(application());setStatus("Draft ready. Review it below, then send it through Discord. Nothing has been submitted.");}}>
    <div className="fieldPair"><label className="fieldLabel">Community or creator name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label className="fieldLabel">Partner type<select value={kind} onChange={e=>setKind(e.target.value)}>{["Minecraft community","Content creator","Server network","PvP community","Modding community","Other relevant project"].map(k=><option key={k}>{k}</option>)}</select></label></div>
    <label className="fieldLabel">Public website, channel, or Discord invite<input required type="url" maxLength={500} placeholder="https://…" value={link} onChange={e=>setLink(e.target.value)}/></label>
    <div className="fieldPair"><label className="fieldLabel">Discord username for contact<input required maxLength={80} value={contact} onChange={e=>setContact(e.target.value)}/></label><label className="fieldLabel">Audience and recent activity · optional<input maxLength={200} placeholder="Members, viewers, events…" value={audience} onChange={e=>setAudience(e.target.value)}/></label></div>
    <label className="fieldLabel">Your collaboration idea<textarea required maxLength={2000} value={idea} onChange={e=>setIdea(e.target.value)} placeholder="What could we create or do together?"/></label>
    <label className="fieldLabel">What can you offer?<textarea required maxLength={1500} value={offer} onChange={e=>setOffer(e.target.value)}/></label>
    <label className="fieldLabel">What would you need from Booger Client?<textarea required maxLength={1500} value={needs} onChange={e=>setNeeds(e.target.value)}/></label>
    <label className="fieldLabel">Partnership rules or requirements · optional<textarea maxLength={1500} value={rules} onChange={e=>setRules(e.target.value)}/></label>
    <label className="partnerConsent"><input required type="checkbox" checked={allowed} onChange={e=>setAllowed(e.target.checked)}/> I can discuss collaborations for this community and have checked its partnership rules.</label>
    <button className="bigButton partnerPrepare" type="submit">Prepare application →</button>
  </form>
  {draft&&<div className="applicationReview"><h3>Review your application</h3><p>Not sent yet. Copy this draft and send it to the team on Discord.</p><label className="fieldLabel">Application draft<textarea readOnly value={draft}/></label><div className="toolActions"><button type="button" onClick={copy}>Copy application</button><button type="button" onClick={download}>Download .txt</button><a href={DISCORD} target="_blank" rel="noopener noreferrer">Open Booger Discord ↗</a></div><p className="smallNote">Changed the form? Use Prepare application again to refresh this draft.</p></div>}
  <p className="partnerStatus" role="status">{status}</p></section></div>;
}
