"use client";
import { useState } from "react";
const issues = "https://github.com/rylofficalacc-prog/booger-client-site/issues";
export default function SupportTools() {
  const [summary,setSummary]=useState(""); const [steps,setSteps]=useState(""); const [expected,setExpected]=useState(""); const [actual,setActual]=useState(""); const [version,setVersion]=useState(""); const [system,setSystem]=useState("Windows 11"); const [error,setError]=useState(""); const [status,setStatus]=useState(""); const [clean,setClean]=useState(""); const [idea,setIdea]=useState("");
  const report=`Booger Client bug report\n\nSummary: ${summary}\nVersion: ${version || "Not provided"}\nSystem: ${system}\n\nSteps to reproduce:\n${steps}\n\nExpected:\n${expected}\n\nActual:\n${actual}`;
  function save(text:string,name:string) { const u=URL.createObjectURL(new Blob([text],{type:"text/plain"}));const a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u); }
  async function copy() { try {await navigator.clipboard.writeText(report);setStatus("Report copied. Paste it into Discord or an issue.");}catch{setStatus("Clipboard unavailable. Download the report instead.");} }
  function redact(text:string) { return text.replace(/(authorization\s*[:=]\s*)(?:bearer\s+)?[^\r\n]+/gi,"$1[REDACTED]").replace(/((?:access[_ -]?token|refresh[_ -]?token|password|client[_ -]?secret|api[_ -]?key|session[_ -]?id|cookie)\s*[\"']?\s*[:=]\s*)[^\r\n]+/gi,"$1[REDACTED]").replace(/\b(?:eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+|gh[pousr]_[A-Za-z0-9_]+|github_pat_[A-Za-z0-9_]+)\b/g,"[TOKEN]").replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,"[EMAIL]").replace(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g,"[IP ADDRESS]").replace(/\b[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}\b/gi,"[UUID]").replace(/[A-Z]:[\\/]Users[\\/][^\\/\s]+/gi,"C:\\Users\\[USER]").replace(/\/(?:home|Users)\/[^/\s]+/g,"/home/[USER]").replace(/https?:\/\/[^\s\"'<>]+/gi,"[URL]"); }
  return <>
    <div className="supportGrid">
      <section className="toolCard" id="bug-report"><p className="eyebrow">Bug Report</p><h2>Help us reproduce it</h2><p>Include what happened and the steps that caused it. Your draft stays in this browser.</p>
        <form onSubmit={e=>{e.preventDefault();save(report,"booger-bug-report.txt");setStatus("Report downloaded. Review it before sharing.");}}>
          <label className="fieldLabel">Short summary<input required maxLength={150} value={summary} onChange={e=>setSummary(e.target.value)}/></label>
          <div className="fieldPair"><label className="fieldLabel">Client / launcher version<input maxLength={60} value={version} onChange={e=>setVersion(e.target.value)} placeholder="Shown in About"/></label><label className="fieldLabel">Operating system<select value={system} onChange={e=>setSystem(e.target.value)}><option>Windows 11</option><option>Windows 10</option><option>Other</option></select></label></div>
          <label className="fieldLabel">Steps to reproduce<textarea required maxLength={4000} value={steps} onChange={e=>setSteps(e.target.value)} placeholder="1. Open the launcher…"/></label>
          <label className="fieldLabel">What did you expect?<textarea required maxLength={2000} value={expected} onChange={e=>setExpected(e.target.value)}/></label>
          <label className="fieldLabel">What actually happened?<textarea required maxLength={2000} value={actual} onChange={e=>setActual(e.target.value)}/></label>
          <div className="toolActions"><button type="submit">Download report</button><button type="button" onClick={copy}>Copy report</button></div>
          <p role="status">{status}</p>
          {summary.trim() && <a className="supportLink" href={`${issues}/new?${new URLSearchParams({title:`[Bug] ${summary}`,body:report})}`} target="_blank" rel="noreferrer">Review on GitHub →</a>}
          <p className="smallNote">GitHub issues are public. Opening the link prepares a draft; you choose whether to submit. Do not include credentials or private account details.</p>
        </form>
      </section>
      <div className="supportStack"><section className="toolCard"><p className="eyebrow">Troubleshooting</p><h2>Start with the error</h2><details><summary>Microsoft sign-in did not finish</summary><p>Check that you completed the Microsoft page with the account that owns Minecraft: Java Edition. Start a fresh sign-in attempt if its code expired. Never send your sign-in code to staff.</p></details><details><summary>The first download stopped</summary><p>Check your internet connection and available disk space, then retry. Keep the exact error message if it happens again.</p></details><details><summary>Minecraft closes while starting</summary><p>Record the client version and error, and try reproducing the problem with extra third-party mods removed. Use the report form to describe what changed.</p></details><details><summary>Windows blocks the installer</summary><p>Check that the file came from the official Download page. Keep security protections enabled and report the warning so the team can investigate.</p></details></section>
      <section className="toolCard"><p className="eyebrow">Private Log Cleaner</p><h2>Review before sharing</h2><p>Choose a text log to remove common credentials, emails, IPv4 addresses, UUIDs, user-folder names and URLs. Processing happens locally; the file is not uploaded.</p><label className="fileButton">Choose .log or .txt<input type="file" accept=".log,.txt,text/plain" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setError("");setClean("");try{if(f.size>2*1024*1024)throw Error("Choose a text log smaller than 2 MB.");const t=await f.text();if(t.includes("\u0000"))throw Error("This does not look like a text log.");setClean(redact(t));}catch(err){setError(err instanceof Error?err.message:"Could not read file.");}e.target.value="";}}/></label><p role="status">{error}</p>{clean&&<><label className="fieldLabel">Cleaned log · editable review<textarea className="logReview" value={clean} onChange={e=>setClean(e.target.value)}/></label><p className="smallNote">Automatic redaction cannot recognize every private detail. Check usernames, server addresses, IPv6 addresses and free text yourself before sharing.</p><div className="toolActions"><button type="button" onClick={()=>save(clean,"booger-log-reviewed.txt")}>Download reviewed log</button><button type="button" onClick={()=>setClean("")}>Clear log</button></div></>}</section></div>
    </div>
    <section className="toolCard feedbackCard" id="feedback"><p className="eyebrow">Community Feedback</p><h2>What should we build next?</h2><p>Check existing requests first. Add a 👍 reaction to an issue to support it, or explain how a new feature would help you.</p><label className="fieldLabel">Your feature idea<input maxLength={150} value={idea} onChange={e=>setIdea(e.target.value)} placeholder="For example, shareable HUD profiles"/></label><div className="toolActions"><a href={issues} target="_blank" rel="noreferrer">Browse requests & vote →</a>{idea.trim()&&<a href={`${issues}/new?${new URLSearchParams({title:`[Feature] ${idea}`,body:"What problem would this solve?\n\nHow should it work?\n\nWho would benefit?\n"})}`} target="_blank" rel="noreferrer">Draft feature request →</a>}<a href="/roadmap">View roadmap →</a></div><p className="smallNote">GitHub sign-in is required to submit or react. Votes guide discussion; they do not guarantee a feature or release date.</p></section>
  </>;
}
